const PupDefaultBoxData = {
  jig: 0,
  totalTime: 0,
  stages: [
    {
      stage: 1,
      status: "",
      infoDrawings: ["/images/box/lead/pass.png"],
      picutresArray: [],
      singlePicture: ["/images/box/lead/new-full-stage/stage1.png"],
      startDate: "",
      endDate: "",
      timer: 0,
    },
    {
      stage: 2,
      status: "",
      infoDrawings: ["/images/box/lead/pass.png"],
      picutresArray: [],
      singlePicture: ["/images/box/lead/new-full-stage/stage2.png"],
      startDate: "",
      endDate: "",
      timer: 0,
    },
    {
      stage: 3,
      status: "",
      infoDrawings: ["/images/box/lead/pass.png"],
      picutresArray: [],
      singlePicture: ["/images/box/lead/new-full-stage/stage3.png"],
      startDate: "",
      endDate: "",
      timer: 0,
    },
    {
      stage: 4,
      status: "",
      infoDrawings: ["/images/box/lead/pass.png"],
      picutresArray: [],
      singlePicture: ["/images/box/lead/new-full-stage/stage4.png"],
      startDate: "",
      endDate: "",
      timer: 0,
    },
  ],
};

const TandemDefaultBoxData = {
  jig: 0,
  totalTime: 0,
  stages: [
    {
      stage: 1,
      status: "",
      infoDrawings: ["/images/box/lead/pass.png"],
      picutresArray: [],
      singlePicture: ["/images/box/tandem/new-full-stage/stage1.png"],
      startDate: "",
      endDate: "",
      timer: 0,
    },
    {
      stage: 2,
      status: "",
      infoDrawings: ["/images/box/lead/pass.png"],
      picutresArray: [],
      singlePicture: ["/images/box/tandem/new-full-stage/stage2.png"],
      startDate: "",
      endDate: "",
      timer: 0,
    },
    {
      stage: 3,
      status: "",
      infoDrawings: ["/images/box/lead/pass.png"],
      picutresArray: [],
      singlePicture: ["/images/box/tandem/new-full-stage/stage3.png"],
      startDate: "",
      endDate: "",
      timer: 0,
    },
    {
      stage: 4,
      status: "",
      infoDrawings: ["/images/box/lead/pass.png"],
      picutresArray: [],
      singlePicture: ["/images/box/tandem/new-full-stage/stage4.png"],
      startDate: "",
      endDate: "",
      timer: 0,
    },
  ],
};

const LeadDefaultBoxData = {
  jig: 0,
  totalTime: 0,
  stages: [
    {
      stage: 1,
      status: "",
      infoDrawings: ["/images/box/lead/pass.png"],
      picutresArray: [],
      singlePicture: ["/images/box/lead/new-full-stage/stage1.png"],
      startDate: "",
      endDate: "",
      timer: 0,
    },
    {
      stage: 2,
      status: "",
      infoDrawings: ["/images/box/lead/pass.png"],
      picutresArray: [],
      singlePicture: ["/images/box/lead/new-full-stage/stage2.png"],
      startDate: "",
      endDate: "",
      timer: 0,
    },
    {
      stage: 3,
      status: "",
      infoDrawings: ["/images/box/lead/pass.png"],
      picutresArray: [],
      singlePicture: ["/images/box/lead/new-full-stage/stage3.png"],
      startDate: "",
      endDate: "",
      timer: 0,
    },
    {
      stage: 4,
      status: "",
      infoDrawings: ["/images/box/lead/pass.png"],
      picutresArray: [],
      singlePicture: ["/images/box/lead/new-full-stage/stage4.png"],
      startDate: "",
      endDate: "",
      timer: 0,
    },
  ],
};

const Tri61TwoHoppersDefaultBoxData = {
  jig: 0,
  totalTime: 0,
  stages: [
    {
      stage: 1,
      status: "",
      infoDrawings: ["/images/box/lead/pass.png"],
      picutresArray: [],
      singlePicture: ["/images/box/Tri2Hop/full-stage/stage1.png"],
      startDate: "",
      endDate: "",
      timer: 0,
    },
    {
      stage: 2,
      status: "",
      infoDrawings: ["/images/box/lead/pass.png"],
      picutresArray: [],
      singlePicture: ["/images/box/Tri2Hop/full-stage/stage2.png"],
      startDate: "",
      endDate: "",
      timer: 0,
    },
    {
      stage: 3,
      status: "",
      infoDrawings: ["/images/box/lead/pass.png"],
      picutresArray: [],
      singlePicture: ["/images/box/Tri2Hop/full-stage/stage3.png"],
      startDate: "",
      endDate: "",
      timer: 0,
    },
    {
      stage: 4,
      status: "",
      infoDrawings: ["/images/box/lead/pass.png"],
      picutresArray: [],
      singlePicture: ["/images/box/Tri2Hop/full-stage/stage4.png"],
      startDate: "",
      endDate: "",
      timer: 0,
    },
  ],
};

const Tri61ThreeHoppersDefaultBoxData = {
  jig: 0,
  totalTime: 0,
  stages: [
    {
      stage: 1,
      status: "",
      infoDrawings: ["/images/box/lead/pass.png"],
      picutresArray: [],
      singlePicture: ["/images/box/Tri3Hop/full-stage/stage1.png"],
      startDate: "",
      endDate: "",
      timer: 0,
    },
    {
      stage: 2,
      status: "",
      infoDrawings: ["/images/box/lead/pass.png"],
      picutresArray: [],
      singlePicture: ["/images/box/Tri3Hop/full-stage/stage2.png"],
      startDate: "",
      endDate: "",
      timer: 0,
    },
    {
      stage: 3,
      status: "",
      infoDrawings: ["/images/box/lead/pass.png"],
      picutresArray: [],
      singlePicture: ["/images/box/Tri3Hop/full-stage/stage3.png"],
      startDate: "",
      endDate: "",
      timer: 0,
    },
    {
      stage: 4,
      status: "",
      infoDrawings: ["/images/box/lead/pass.png"],
      picutresArray: [],
      singlePicture: ["/images/box/Tri3Hop/full-stage/stage4.png"],
      startDate: "",
      endDate: "",
      timer: 0,
    },
  ],
};

const Tri72TwoHoppersDefaultBoxData = {
  jig: 0,
  totalTime: 0,
  stages: [
    {
      stage: 1,
      status: "",
      infoDrawings: ["/images/box/lead/pass.png"],
      picutresArray: [],
      singlePicture: ["/images/box/Tri2Hop/full-stage/stage1.png"],
      startDate: "",
      endDate: "",
      timer: 0,
    },
    {
      stage: 2,
      status: "",
      infoDrawings: ["/images/box/lead/pass.png"],
      picutresArray: [],
      singlePicture: ["/images/box/Tri2Hop/full-stage/stage2.png"],
      startDate: "",
      endDate: "",
      timer: 0,
    },
    {
      stage: 3,
      status: "",
      infoDrawings: ["/images/box/lead/pass.png"],
      picutresArray: [],
      singlePicture: ["/images/box/Tri2Hop/full-stage/stage3.png"],
      startDate: "",
      endDate: "",
      timer: 0,
    },
    {
      stage: 4,
      status: "",
      infoDrawings: ["/images/box/lead/pass.png"],
      picutresArray: [],
      singlePicture: ["/images/box/Tri2Hop/full-stage/stage4.png"],
      startDate: "",
      endDate: "",
      timer: 0,
    },
  ],
};

const defaultBoxesData = {
  Pup: PupDefaultBoxData,
  Tandem: TandemDefaultBoxData,
  Lead: LeadDefaultBoxData,
  Tri61TwoHoppers: Tri61TwoHoppersDefaultBoxData,
  Tri61ThreeHoppers: Tri61ThreeHoppersDefaultBoxData,
  Tri72TwoHoppers: Tri72TwoHoppersDefaultBoxData,
  "4 Axle": Tri72TwoHoppersDefaultBoxData,
};

export default defaultBoxesData;
