const wallsData = {
  pupWalls: [
    {
      wallType: "Side Wall - Driver",
      defaultImage: "/images/walls/defaultPup/driver",
      completedImage: "/images/walls/completedPup/driver",
      wallDrawings: [
        "/images/pup/1300-PUP-1.png",
        "/images/pup/1300-PUP-2.png",
        "/images/pup/1300-PUP-3.png",
        "/images/pup/1300-PUP-4.png",
        "/images/pup/1300-PUP-5.png",
      ],
      specialRequirements: "",
      status: "notStarted",
      startedDate: null,
      completedDate: null,
      isActive: false,
      firstStart: false,
      time: 0,
    },
    {
      wallType: "Side Wall - Passenger",
      defaultImage: "/images/walls/defaultPup/pass",
      completedImage: "/images/walls/completedPup/pass",
      wallDrawings: [
        "/images/pup/1300-PUP-1.png",
        "/images/pup/1300-PUP-2.png",
        "/images/pup/1300-PUP-3.png",
        "/images/pup/1300-PUP-4.png",
        "/images/pup/1300-PUP-5.png",
      ],
      specialRequirements: "",
      status: "notStarted",
      startedDate: null,
      completedDate: null,
      isActive: false,
      firstStart: false,
      time: 0,
    },
    {
      wallType: "Front Top",
      defaultImage: "/images/walls/defaultPup/top-front",
      completedImage: "/images/walls/completedPup/top-front",
      wallDrawings: ["/images/pup/1301-PUP-1.png"],
      specialRequirements: "",
      status: "notStarted",
      startedDate: null,
      completedDate: null,
      isActive: false,
      firstStart: false,
      time: 0,
    },
    {
      wallType: "Rear Top",
      defaultImage: "/images/walls/defaultPup/top-rear",
      completedImage: "/images/walls/completedPup/top-rear",
      wallDrawings: ["/images/pup/1304-PUP-1.png"],
      specialRequirements: "",
      status: "notStarted",
      startedDate: null,
      completedDate: null,
      isActive: false,
      firstStart: false,
      time: 0,
    },
    {
      wallType: "Front Slope",
      defaultImage: "/images/walls/defaultPup/front-slope",
      completedImage: "/images/walls/completedPup/front-slope",
      wallDrawings: ["/images/pup/1302-PUP-1.png"],
      specialRequirements: "",
      status: "notStarted",
      startedDate: null,
      completedDate: null,
      isActive: false,
      firstStart: false,
      time: 0,
    },
    {
      wallType: "Rear Slope",
      defaultImage: "/images/walls/defaultPup/rear-slope",
      completedImage: "/images/walls/completedPup/rear-slope",
      wallDrawings: ["/images/pup/1305-PUP-1.png"],
      specialRequirements: "",
      status: "notStarted",
      startedDate: null,
      completedDate: null,
      isActive: false,
      firstStart: false,
      time: 0,
    },
    {
      wallType: "Mid Wall",
      defaultImage: "/images/walls/defaultPup/midwall",
      completedImage: "/images/walls/completedPup/midwall",
      wallDrawings: [
        "/images/pup/1303-PUP-1.png",
        "/images/pup/1303-PUP-2.png",
      ],
      specialRequirements: "",
      status: "notStarted",
      startedDate: null,
      completedDate: null,
      isActive: false,
      firstStart: false,
      time: 0,
    },
  ],
};

export default wallsData;
