const boxData = [
    {
      "_id": { "$oid": "663a737a72e2393d6569d0a0" },
      "WO": "95511",
      "trailerType": "Lead",
      "jig": { "$numberInt": "1" },
      "specifications": {},
      "materials": {},
      "walls": {},
      "stages": [
        {
          "stage": { "$numberInt": "1" },
          "status": "complete",
          "drawings": "/images/box/lead/pass",
          "startDate": "",
          "endDate": "",
          "timer": { "$numberInt": "0" }
        },
        {
          "stage": { "$numberInt": "2" },
          "drawings": "/images/box/lead/pass",
          "startDate": "",
          "endDate": "",
          "timer": { "$numberInt": "0" },
          "status": "running"
        },
        {
          "drawings": "/images/box/lead/pass",
          "startDate": "",
          "endDate": "",
          "timer": { "$numberInt": "0" },
          "status": ""
        },
        {
          "drawings": "/images/box/lead/pass",
          "startDate": "",
          "endDate": "",
          "timer": { "$numberInt": "0" },
          "status": ""
        }
      ],
      "sections": [
        {
          "sectionType": "Side Wall - Driver",
          "stage1": "/images/box/lead/driver",
          "stage4": "/images/box/lead/tarp-bows-steps",
          "drawingURL": "",
          "currentStage": null,
          "stage1StartTime": null,
          "stage1EndTime": null,
          "stage1Timer": null,
          "special": false,
          "status": "notStarted",
          "startedDate": null,
          "completedDate": null,
          "isActive": false,
          "firstStart": false,
          "time": { "$numberInt": "0" }
        },
        {
          "sectionType": "Side Wall - Passenger",
          "stage1": "/images/box/lead/pass",
          "stage3": "/images/box/lead/hopper-panels",
          "stage4": "/images/box/lead/filler-strips",
          "drawingURL": "",
          "special": false,
          "status": "notStarted",
          "startedDate": null,
          "completedDate": null,
          "isActive": false,
          "firstStart": false,
          "time": { "$numberInt": "0" }
        },
        {
          "sectionType": "Front Slope",
          "stage1": "/images/box/lead/front-6",
          "stage2": "/images/box/lead/front-slope",
          "stage3": "/images/box/lead/front-w",
          "drawingURL": "",
          "special": false,
          "status": "notStarted",
          "startedDate": null,
          "completedDate": null,
          "isActive": false,
          "firstStart": false,
          "time": { "$numberInt": "0" }
        },
        {
          "sectionType": "Rear Slope",
          "stage1": "/images/box/lead/rear-6",
          "stage2": "/images/box/lead/rear-slope",
          "stage3": "/images/box/lead/rear-w",
          "drawingURL": "",
          "special": false,
          "status": "notStarted",
          "startedDate": null,
          "completedDate": null,
          "isActive": false,
          "firstStart": false,
          "time": { "$numberInt": "0" }
        },
        {
          "sectionType": "Mid Wall",
          "stage1": "/images/box/lead/stage-1",
          "stage2": "/images/box/lead/stage-2",
          "stage3": "/images/box/lead/stage-3",
          "stage4": "/images/box/lead/stage-4",
          "drawingURL": "",
          "special": false,
          "status": "notStarted",
          "startedDate": null,
          "completedDate": null,
          "isActive": false,
          "firstStart": false,
          "time": { "$numberInt": "0" }
        }
      ]
    },
    
    {
      WO: "45511",
      trailerType: "Lead",
      sections: [
        {
          sectionType: "Side Wall - Driver",
          stage1: "/images/box/lead/driver",
          stage4: "/images/box/lead/tarp-bows-steps",
          drawingURL: "",
          special: false,
          status: "notStarted",
          startedDate: null,
          completedDate: null,
          isActive: false,
          firstStart: false,
          time: 0,
        },
        {
          sectionType: "Side Wall - Passenger",
          stage1: "/images/box/lead/pass",
          stage3: "/images/box/lead/hopper-panels",
          stage4: "/images/box/lead/filler-strips",
          drawingURL: "",
          special: false,
          status: "notStarted",
          startedDate: null,
          completedDate: null,
          isActive: false,
          firstStart: false,
          time: 0,
        },
        {
          sectionType: "Front Slope",
          stage1: "/images/box/lead/front-6",
          stage2: "/images/box/lead/front-slope",
          stage3: "/images/box/lead/front-w",
          drawingURL: "",
          special: false,
          status: "notStarted",
          startedDate: null,
          completedDate: null,
          isActive: false,
          firstStart: false,
          time: 0,
        },
        {
          sectionType: "Rear Slope",
          stage1: "/images/box/lead/rear-6",
          stage2: "/images/box/lead/rear-slope",
          stage3: "/images/box/lead/rear-w",
          drawingURL: "",
          special: false,
          status: "notStarted",
          startedDate: null,
          completedDate: null,
          isActive: false,
          firstStart: false,
          time: 0,
        },
        {
          sectionType: "Mid Wall",
          stage1: "/images/box/lead/stage-1",
          stage2: "/images/box/lead/stage-2",
          stage3: "/images/box/lead/stage-3",
          stage4: "/images/box/lead/stage-4",
          drawingURL: "",
          special: false,
          status: "notStarted",
          startedDate: null,
          completedDate: null,
          isActive: false,
          firstStart: false,
          time: 0,
        },
      ],
    },
    {
      WO: "45511",
      trailerType: "Pup",
      sections: [
        {
          sectionType: "Side Wall - Driver",
          stage1: "/images/box/pup/driver",
          stage4: "/images/box/pup/tarp-bows-steps",
          drawingURL: "",
          special: false,
          status: "notStarted",
          startedDate: null,
          completedDate: null,
          isActive: false,
          firstStart: false,
          time: 0,
        },
        {
          sectionType: "Side Wall - Passenger",
          stage1: "/images/box/pup/pass",
          stage3: "/images/box/pup/hopper-panels",
          stage4: "/images/box/pup/filler-strips",
          drawingURL: "",
          special: false,
          status: "notStarted",
          startedDate: null,
          completedDate: null,
          isActive: false,
          firstStart: false,
          time: 0,
        },
        {
          sectionType: "Front Slope",
          stage1: "/images/box/pup/front-6",
          stage2: "/images/box/pup/front-slope",
          stage3: "/images/box/pup/front-w",
          drawingURL: "",
          special: false,
          status: "notStarted",
          startedDate: null,
          completedDate: null,
          isActive: false,
          firstStart: false,
          time: 0,
        },
        {
          sectionType: "Rear Slope",
          stage1: "/images/box/pup/rear-6",
          stage2: "/images/box/pup/rear-slope",
          stage3: "/images/box/pup/rear-w",
          drawingURL: "",
          special: false,
          status: "notStarted",
          startedDate: null,
          completedDate: null,
          isActive: false,
          firstStart: false,
          time: 0,
        },
        {
          sectionType: "Mid Wall",
          stage1: "/images/box/pup/stage-1",
          stage2: "/images/box/pup/stage-2",
          stage3: "/images/box/pup/stage-3",
          stage4: "/images/box/pup/stage-4",
          drawingURL: "",
          special: false,
          status: "notStarted",
          startedDate: null,
          completedDate: null,
          isActive: false,
          firstStart: false,
          time: 0,
        },
      ],
    },
    {
      WO: "45511",
      trailerType: "Tri2Hop",
      sections: [
        {
          sectionType: "Side Wall - Driver",
          stage1: "/images/box/Tri2Hop/driver",
          stage4: "/images/box/Tri2Hop/tarp-bows-steps",
          drawingURL: "",
          special: false,
          status: "notStarted",
          startedDate: null,
          completedDate: null,
          isActive: false,
          firstStart: false,
          time: 0,
        },
        {
          sectionType: "Side Wall - Passenger",
          stage1: "/images/box/Tri2Hop/pass",
          stage3: "/images/box/Tri2Hop/hopper-panels",
          stage4: "/images/box/Tri2Hop/filler-strips",
          drawingURL: "",
          special: false,
          status: "notStarted",
          startedDate: null,
          completedDate: null,
          isActive: false,
          firstStart: false,
          time: 0,
        },
        {
          sectionType: "Front Slope",
          stage1: "/images/box/Tri2Hop/front-6",
          stage2: "/images/box/Tri2Hop/front-slope",
          stage3: "/images/box/Tri2Hop/front-w",
          drawingURL: "",
          special: false,
          status: "notStarted",
          startedDate: null,
          completedDate: null,
          isActive: false,
          firstStart: false,
          time: 0,
        },
        {
          sectionType: "Rear Slope",
          stage1: "/images/box/Tri2Hop/rear-6",
          stage2: "/images/box/Tri2Hop/rear-slope",
          stage3: "/images/box/Tri2Hop/rear-w",
          drawingURL: "",
          special: false,
          status: "notStarted",
          startedDate: null,
          completedDate: null,
          isActive: false,
          firstStart: false,
          time: 0,
        },
        {
          sectionType: "Mid Wall",
          stage1: "/images/box/Tri2Hop/stage-1",
          stage2: "/images/box/Tri2Hop/stage-2",
          stage3: "/images/box/Tri2Hop/stage-3",
          stage4: "/images/box/Tri2Hop/stage-4",
          drawingURL: "",
          special: false,
          status: "notStarted",
          startedDate: null,
          completedDate: null,
          isActive: false,
          firstStart: false,
          time: 0,
        },
      ],
    },
    {
      WO: "45511",
      trailerType: "Tri3Hop",
      sections: [
        {
          sectionType: "Side Wall - Driver",
          stage1: "/images/box/Tri3Hop/driver",
          stage4: "/images/box/Tri3Hop/tarp-bows-steps",
          drawingURL: "",
          special: false,
          status: "notStarted",
          startedDate: null,
          completedDate: null,
          isActive: false,
          firstStart: false,
          time: 0,
        },
        {
          sectionType: "Side Wall - Passenger",
          stage1: "/images/box/Tri3Hop/pass",
          stage3: "/images/box/Tri3Hop/hopper-panels",
          stage4: "/images/box/Tri3Hop/filler-strips",
          drawingURL: "",
          special: false,
          status: "notStarted",
          startedDate: null,
          completedDate: null,
          isActive: false,
          firstStart: false,
          time: 0,
        },
        {
          sectionType: "Front Slope",
          stage1: "/images/box/Tri3Hop/front-6",
          stage2: "/images/box/Tri3Hop/front-slope",
          stage3: "/images/box/Tri3Hop/front-w",
          drawingURL: "",
          special: false,
          status: "notStarted",
          startedDate: null,
          completedDate: null,
          isActive: false,
          firstStart: false,
          time: 0,
        },
        {
          sectionType: "Rear Slope",
          stage1: "/images/box/Tri3Hop/rear-6",
          stage2: "/images/box/Tri3Hop/rear-slope",
          stage3: "/images/box/Tri3Hop/rear-w",
          drawingURL: "",
          special: false,
          status: "notStarted",
          startedDate: null,
          completedDate: null,
          isActive: false,
          firstStart: false,
          time: 0,
        },
        {
          sectionType: "Mid Wall",
          stage1: "/images/box/Tri3Hop/stage-1",
          stage2: "/images/box/Tri3Hop/stage-2",
          stage3: "/images/box/Tri3Hop/stage-3",
          stage4: "/images/box/Tri3Hop/stage-4",
          drawingURL: "",
          special: false,
          status: "notStarted",
          startedDate: null,
          completedDate: null,
          isActive: false,
          firstStart: false,
          time: 0,
        },
      ],
    },
    {
      WO: "45511",
      trailerType: "Tandem",
      sections: [
        {
          sectionType: "Side Wall - Driver",
          stage1: "/images/box/tandem/driver",
          stage4: "/images/box/tandem/tarp-bows-steps",
          drawingURL: "",
          special: false,
          status: "notStarted",
          startedDate: null,
          completedDate: null,
          isActive: false,
          firstStart: false,
          time: 0,
        },
        {
          sectionType: "Side Wall - Passenger",
          stage1: "/images/box/tandem/pass",
          stage3: "/images/box/tandem/hopper-panels",
          stage4: "/images/box/tandem/filler-strips",
          drawingURL: "",
          special: false,
          status: "notStarted",
          startedDate: null,
          completedDate: null,
          isActive: false,
          firstStart: false,
          time: 0,
        },
        {
          sectionType: "Front Slope",
          stage1: "/images/box/tandem/front-6",
          stage2: "/images/box/tandem/front-slope",
          stage3: "/images/box/tandem/front-w",
          drawingURL: "",
          special: false,
          status: "notStarted",
          startedDate: null,
          completedDate: null,
          isActive: false,
          firstStart: false,
          time: 0,
        },
        {
          sectionType: "Rear Slope",
          stage1: "/images/box/tandem/rear-6",
          stage2: "/images/box/tandem/rear-slope",
          stage3: "/images/box/tandem/rear-w",
          drawingURL: "",
          special: false,
          status: "notStarted",
          startedDate: null,
          completedDate: null,
          isActive: false,
          firstStart: false,
          time: 0,
        },
        {
          sectionType: "Mid Wall",
          stage1: "/images/box/tandem/stage-1",
          stage2: "/images/box/tandem/stage-2",
          stage3: "/images/box/tandem/stage-3",
          stage4: "/images/box/tandem/stage-4",
          drawingURL: "",
          special: false,
          status: "notStarted",
          startedDate: null,
          completedDate: null,
          isActive: false,
          firstStart: false,
          time: 0,
        },
      ],
    },
  ];
  
  export default boxData;