const leadWallsTaskList = [
  {
    wallName: "Pass Side 1300-102",
    wallDrawings: [
      "/images/lead/1300-LEAD-1.png",
      "/images/lead/1300-LEAD-2.png",
      "/images/lead/1300-LEAD-3.png",
      "/images/lead/1300-LEAD-4.png",
      "/images/lead/1300-LEAD-5.png",
    ],
    specialRequirements: "",
    wallStatus: "Not Started",
    tasksList: [
      {
        task: "Cut Panels",
        taskEs: "Cortar Paneles",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Cut + Assemble Rails and Panels",
        taskEs: "Cortar + Ensamblar marcos y Paneles",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Weld First Side",
        taskEs: "Soldar Primer Lado",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Flip + Cover + Weld Second Side",
        taskEs: "Voltear + Cubrir + Soldar Segundo Lado",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Store Wall",
        taskEs: "Guardar Pared",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
    ],
  },
  {
    wallName: "Driver Side 1300-101",
    wallDrawings: [
      "/images/lead/1300-LEAD-1.png",
      "/images/lead/1300-LEAD-2.png",
      "/images/lead/1300-LEAD-3.png",
      "/images/lead/1300-LEAD-4.png",
      "/images/lead/1300-LEAD-5.png",
    ],
    specialRequirements: "",
    wallStatus: "Not Started",
    tasksList: [
      {
        task: "Cut Panels",
        taskEs: "Cortar Paneles",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Cut + Assemble Rails and Panels",
        taskEs: "Cortar + Ensamblar marcos y Paneles",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Weld First Side",
        taskEs: "Soldar Primer Lado",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Flip + Cover + Weld Second Side",
        taskEs: "Voltear + Cubrir + Soldar Segundo Lado",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Store Wall",
        taskEs: "Guardar Pared",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
    ],
  },
  {
    wallName: "Front Top 1301-101",
    wallDrawings: ["/images/lead/1301-LEAD-1.png"],
    specialRequirements: "",
    wallStatus: "Not Started",
    tasksList: [
      {
        task: "Cut Panels",
        taskEs: "Cortar Paneles",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Weld Panels",
        taskEs: "Soldar Paneles",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Remove welds and grind",
        taskEs: "Demoler Soldaduras + Pulir",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
    ],
  },
  {
    wallName: "Rear Top 1304-101",
    wallDrawings: ["/images/lead/1304-LEAD-1.png"],
    specialRequirements: "",
    wallStatus: "Not Started",
    tasksList: [
      {
        task: "Cut Panels",
        taskEs: "Cortar Paneles",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Weld Panels",
        taskEs: "Soldar Paneles",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Remove welds and grind",
        taskEs: "Demoler Soldaduras + Pulir",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
    ],
  },
  {
    wallName: "Front Sloped 1302-101",
    wallDrawings: ["/images/lead/1302-LEAD-1.png"],
    specialRequirements: "",
    wallStatus: "Not Started",
    tasksList: [
      {
        task: "Cut Panels",
        taskEs: "Cortar Paneles",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Weld Panels",
        taskEs: "Soldar Paneles",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Remove welds and grind",
        taskEs: "Demoler Soldaduras + Pulir",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
    ],
  },
  {
    wallName: "Rear Sloped 1305-101",
    wallDrawings: ["/images/lead/1305-LEAD-1.png"],
    specialRequirements: "",
    wallStatus: "Not Started",
    tasksList: [
      {
        task: "Cut Panels",
        taskEs: "Cortar Paneles",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Weld Panels",
        taskEs: "Soldar Paneles",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Remove welds and grind",
        taskEs: "Demoler Soldaduras + Pulir",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
    ],
  },
  {
    wallName: "Middle Wall 1303-101",
    wallDrawings: [
      "/images/lead/1303-LEAD-1.png",
      "/images/lead/1303-LEAD-2.png",
    ],
    specialRequirements: "",
    wallStatus: "Not Started",
    tasksList: [
      {
        task: "Cut Panels",
        taskEs: "Cortar Paneles",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Weld Panels both sides",
        taskEs: "Soldar Paneles a Ambos Lados",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
    ],
  },
];

export default leadWallsTaskList;
