const tandemWallsTasksList = [
  {
    wallName: "Pass Side 1300-102",
    wallDrawings: [
      "/images/tandem/1300-TAN-1.png",
      "/images/tandem/1300-TAN-2.png",
      "/images/tandem/1300-TAN-3.png",
      "/images/tandem/1300-TAN-4.png",
    ],
    specialRequirements: "",
    wallStatus: "Not Started",
    tasksList: [
      {
        task: "Cut Panels",
        taskEs: "Cortar Paneles",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Cut + Assemble Rails and Panels",
        taskEs: "Cortar + Ensamblar marcos y Paneles",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Weld First Side",
        taskEs: "Soldar Primer Lado",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Flip + Cover + Weld Second Side",
        taskEs: "Voltear + Cubrir + Soldar Segundo Lado",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Store Wall",
        taskEs: "Guardar Pared",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
    ],
  },
  {
    wallName: "Driver Side 1300-101",
    wallDrawings: [
      "/images/tandem/1300-TAN-1.png",
      "/images/tandem/1300-TAN-2.png",
      "/images/tandem/1300-TAN-3.png",
      "/images/tandem/1300-TAN-4.png",
    ],
    specialRequirements: "",
    wallStatus: "Not Started",
    tasksList: [
      {
        task: "Cut Panels",
        taskEs: "Cortar Paneles",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Cut + Assemble Rails and Panels",
        taskEs: "Cortar + Ensamblar marcos y Paneles",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Weld First Side",
        taskEs: "Soldar Primer Lado",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Flip + Cover + Weld Second Side",
        taskEs: "Voltear + Cubrir + Soldar Segundo Lado",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Store Wall",
        taskEs: "Guardar Pared",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
    ],
  },
  {
    wallName: "Front Sloped 1302-101",
    wallDrawings: ["/images/tandem/1302-TAN-1.png"],
    specialRequirements: "",
    wallStatus: "Not Started",
    tasksList: [
      {
        task: "Cut Panels",
        taskEs: "Cortar Paneles",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
      },
      {
        task: "Weld Panels",
        taskEs: "Soldar Paneles",
        started: "",
        completed: "",
        procedureLink: "link",
        timerActive: false,
      },
      {
        task: "Remove welds and grind",
        taskEs: "Demoler Soldaduras + Pulir",
        started: "",
        completed: "",
        procedureLink: "link",
        pauses: [],
      },
    ],
  },
  {
    wallName: "Rear Sloped 1305-101",
    wallDrawings: ["/images/tandem/1305-TAN-1.png"],
    specialRequirements: "",
    wallStatus: "Not Started",
    tasksList: [
      {
        task: "Cut Panels",
        taskEs: "Cortar Paneles",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Weld Panels",
        taskEs: "Soldar Paneles",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Remove welds and grind",
        taskEs: "Demoler Soldaduras + Pulir",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
    ],
  },
  {
    wallName: "Middle Wall 1303-101",
    wallDrawings: ["/images/tandem/1303-TAN-1.png"],
    specialRequirements: "",
    wallStatus: "Not Started",
    tasksList: [
      {
        task: "Cut Panels",
        taskEs: "Cortar Paneles",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Weld Panels both sides",
        taskEs: "Soldar Paneles a Ambos Lados",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
    ],
  },
];

export default tandemWallsTasksList;
