const tri2HWallsTasks = [
  {
    wallName: "Pass Side 1300-102",
    wallDrawings: [
      "/images/tri/1300-TRI-1.png",
      "/images/tri/1300-TRI-2.png",
      "/images/tri/1300-TRI-3.png",
      "/images/tri/1300-TRI-4.png",
      "/images/tri/1300-TRI-5.png",
      "/images/tri/1300-TRI-6.png",
    ],
    specialRequirements: "",
    wallStatus: "Not Started",
    tasksList: [
      {
        task: "Cut Panels",
        taskEs: "Cortar Paneles",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Cut + Assemble Rails and Panels",
        taskEs: "Cortar + Ensamblar marcos y Paneles",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Weld First Side",
        taskEs: "Soldar Primer Lado",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Flip + Cover + Weld Second Side",
        taskEs: "Voltear + Cubrir + Soldar Segundo Lado",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Store Wall",
        taskEs: "Guardar Pared",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
    ],
  },
  {
    wallName: "Driver Side 1300-101",
    wallDrawings: [
      "/images/tri/1300-TRI-1.png",
      "/images/tri/1300-TRI-2.png",
      "/images/tri/1300-TRI-3.png",
      "/images/tri/1300-TRI-4.png",
      "/images/tri/1300-TRI-5.png",
      "/images/tri/1300-TRI-6.png",
    ],
    specialRequirements: "",
    wallStatus: "Not Started",
    tasksList: [
      {
        task: "Cut Panels",
        taskEs: "Cortar Paneles",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Cut + Assemble Rails and Panels",
        taskEs: "Cortar + Ensamblar marcos y Paneles",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Weld First Side",
        taskEs: "Soldar Primer Lado",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Flip + Cover + Weld Second Side",
        taskEs: "Voltear + Cubrir + Soldar Segundo Lado",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Store Wall",
        taskEs: "Guardar Pared",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
    ],
  },
  {
    wallName: "Front Sloped 1302-101",
    wallDrawings: ["/images/tri/1302-TRI-1.png"],
    specialRequirements: "",
    wallStatus: "Not Started",
    tasksList: [
      {
        task: "Cut Panels",
        taskEs: "Cortar Paneles",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Weld Panels",
        taskEs: "Soldar Paneles",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Remove welds and grind",
        taskEs: "Demoler Soldaduras + Pulir",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
    ],
  },
  {
    wallName: "Rear Sloped 1305-101",
    wallDrawings: ["/images/tri/1305-TRI-1.png"],
    specialRequirements: "",
    wallStatus: "Not Started",
    tasksList: [
      {
        task: "Cut Panels",
        taskEs: "Cortar Paneles",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Weld Panels",
        taskEs: "Soldar Paneles",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Remove welds and grind",
        taskEs: "Demoler Soldaduras + Pulir",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
    ],
  },
  {
    wallName: "Middle Wall 1303-101",
    wallDrawings: ["/images/tri/1303-TRI-2HOPPERSMIDWALL-1.png"],
    specialRequirements: "",
    wallStatus: "Not Started",
    tasksList: [
      {
        task: "Cut Panels",
        taskEs: "Cortar Paneles",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
      {
        task: "Weld Panels both sides",
        taskEs: "Soldar Paneles a Ambos Lados",
        started: "",
        completed: "",
        procedureLink: "link",
        savedSeconds: 0,
        timerActive: false,
        pauses: [],
      },
    ],
  },
];

export default tri2HWallsTasks;
