const wallsData = [
  {
    dateRequired: null,
    WO: "45563",
    trailerType: "Lead",
    walls: [
      {
        wallType: "Side Wall - Driver",
        defaultImage: "/images/walls/defaultLead/driver",
        completedImage: "/images/walls/completedLead/driver",
        wallDrawings: [
          "/images/lead/1300-LEAD-1.png",
          "/images/lead/1300-LEAD-2.png",
          "/images/lead/1300-LEAD-3.png",
          "/images/lead/1300-LEAD-4.png",
          "/images/lead/1300-LEAD-5.png",
        ],
        specialRequirements: "",
        status: "notStarted",
        startedDate: null,
        completedDate: null,
        isActive: false,
        firstStart: false,
        time: 0,
      },
      {
        wallType: "Side Wall - Passenger",
        defaultImage: "/images/walls/defaultLead/pass",
        completedImage: "/images/walls/completedLead/pass",
        wallDrawings: [
          "/images/lead/1300-LEAD-1.png",
          "/images/lead/1300-LEAD-2.png",
          "/images/lead/1300-LEAD-3.png",
          "/images/lead/1300-LEAD-4.png",
          "/images/lead/1300-LEAD-5.png",
        ],
        specialRequirements: "",
        status: "notStarted",
        startedDate: null,
        completedDate: null,
        isActive: false,
        firstStart: false,
        time: 0,
      },
      {
        wallType: "Front Top",
        defaultImage: "/images/walls/defaultLead/top-front",
        completedImage: "/images/walls/completedLead/top-front",
        wallDrawings: ["/images/lead/1301-LEAD-1.png"],
        specialRequirements: "",
        status: "notStarted",
        startedDate: null,
        completedDate: null,
        isActive: false,
        firstStart: false,
        time: 0,
      },
      {
        wallType: "Rear Top",
        defaultImage: "/images/walls/defaultLead/top-rear",
        completedImage: "/images/walls/completedLead/top-rear",
        wallDrawings: ["/images/lead/1304-LEAD-1.png"],
        specialRequirements: "",
        status: "notStarted",
        startedDate: null,
        completedDate: null,
        isActive: false,
        firstStart: false,
        time: 0,
      },
      {
        wallType: "Front Slope",
        defaultImage: "/images/walls/defaultLead/front-slope",
        completedImage: "/images/walls/completedLead/front-slope",
        wallDrawings: ["/images/lead/1302-LEAD-1.png"],
        specialRequirements: "",
        status: "notStarted",
        startedDate: null,
        completedDate: null,
        isActive: false,
        firstStart: false,
        time: 0,
      },
      {
        wallType: "Rear Slope",
        defaultImage: "/images/walls/defaultLead/rear-slope",
        completedImage: "/images/walls/completedLead/rear-slope",
        wallDrawings: ["/images/lead/1305-LEAD-1.png"],
        specialRequirements: "",
        status: "notStarted",
        startedDate: null,
        completedDate: null,
        isActive: false,
        firstStart: false,
        time: 0,
      },
      {
        wallType: "Mid Wall",
        defaultImage: "/images/walls/defaultLead/midwall",
        completedImage: "/images/walls/completedLead/midwall",
        wallDrawings: ["/images/lead/1303-LEAD-1.png"],
        specialRequirements: "",
        status: "notStarted",
        startedDate: null,
        completedDate: null,
        isActive: false,
        firstStart: false,
        time: 0,
      },
    ],
  },
  {
    dateRequired: null,
    WO: "45563",
    trailerType: "Pup",
    walls: [
      {
        wallType: "Side Wall - Driver",
        defaultImage: "/images/walls/defaultPup/driver",
        completedImage: "/images/walls/completedPup/driver",
        wallDrawings: [
          "/images/pup/1300-PUP-1.png",
          "/images/pup/1300-PUP-2.png",
          "/images/pup/1300-PUP-3.png",
          "/images/pup/1300-PUP-4.png",
          "/images/pup/1300-PUP-5.png",
        ],
        specialRequirements: "",
        status: "notStarted",
        startedDate: null,
        completedDate: null,
        isActive: false,
        firstStart: false,
        time: 0,
      },
      {
        wallType: "Side Wall - Passenger",
        defaultImage: "/images/walls/defaultPup/pass",
        completedImage: "/images/walls/completedPup/pass",
        wallDrawings: [
          "/images/pup/1300-PUP-1.png",
          "/images/pup/1300-PUP-2.png",
          "/images/pup/1300-PUP-3.png",
          "/images/pup/1300-PUP-4.png",
          "/images/pup/1300-PUP-5.png",
        ],
        specialRequirements: "",
        status: "notStarted",
        startedDate: null,
        completedDate: null,
        isActive: false,
        firstStart: false,
        time: 0,
      },
      {
        wallType: "Front Top",
        defaultImage: "/images/walls/defaultPup/top-front",
        completedImage: "/images/walls/completedPup/top-front",
        wallDrawings: ["/images/pup/1301-PUP-1.png"],
        specialRequirements: "",
        status: "notStarted",
        startedDate: null,
        completedDate: null,
        isActive: false,
        firstStart: false,
        time: 0,
      },
      {
        wallType: "Rear Top",
        defaultImage: "/images/walls/defaultPup/top-rear",
        completedImage: "/images/walls/completedPup/top-rear",
        wallDrawings: ["/images/pup/1304-PUP-1.png"],
        specialRequirements: "",
        status: "notStarted",
        startedDate: null,
        completedDate: null,
        isActive: false,
        firstStart: false,
        time: 0,
      },
      {
        wallType: "Front Slope",
        defaultImage: "/images/walls/defaultPup/front-slope",
        completedImage: "/images/walls/completedPup/front-slope",
        wallDrawings: ["/images/pup/1302-PUP-1.png"],
        specialRequirements: "",
        status: "notStarted",
        startedDate: null,
        completedDate: null,
        isActive: false,
        firstStart: false,
        time: 0,
      },
      {
        wallType: "Rear Slope",
        defaultImage: "/images/walls/defaultPup/rear-slope",
        completedImage: "/images/walls/completedPup/rear-slope",
        wallDrawings: ["/images/pup/1305-PUP-1.png"],
        specialRequirements: "",
        status: "notStarted",
        startedDate: null,
        completedDate: null,
        isActive: false,
        firstStart: false,
        time: 0,
      },
      {
        wallType: "Mid Wall",
        defaultImage: "/images/walls/defaultPup/midwall",
        completedImage: "/images/walls/completedPup/midwall",
        wallDrawings: ["/images/pup/1303-PUP-1.png"],
        specialRequirements: "",
        status: "notStarted",
        startedDate: null,
        completedDate: null,
        isActive: false,
        firstStart: false,
        time: 0,
      },
    ],
  },
  {
    dateRequired: null,
    WO: "45993",
    trailerType: "Tri 2 Hop",
    walls: [
      {
        wallType: "Side Wall - Driver",
        defaultImage: "/images/walls/defaultTri2Hop/driver",
        completedImage: "/images/walls/completedTri2Hop/driver",
        wallDrawings: [
          "/images/tri/1300-TRI-1.png",
          "/images/tri/1300-TRI-2.png",
          "/images/tri/1300-TRI-3.png",
          "/images/tri/1300-TRI-4.png",
          "/images/tri/1300-TRI-5.png",
          "/images/tri/1300-TRI-6.png",
        ],
        specialRequirements: "",
        status: "notStarted",
        startedDate: null,
        completedDate: null,
        isActive: false,
        firstStart: false,
        time: 0,
      },
      {
        wallType: "Side Wall - Passenger",
        defaultImage: "/images/walls/defaultTri2Hop/pass",
        completedImage: "/images/walls/completedTri2Hop/pass",
        wallDrawings: [
          "/images/tri/1300-TRI-1.png",
          "/images/tri/1300-TRI-2.png",
          "/images/tri/1300-TRI-3.png",
          "/images/tri/1300-TRI-4.png",
          "/images/tri/1300-TRI-5.png",
          "/images/tri/1300-TRI-6.png",
        ],
        specialRequirements: "",
        status: "notStarted",
        startedDate: null,
        completedDate: null,
        isActive: false,
        firstStart: false,
        time: 0,
      },
      {
        wallType: "Front Slope",
        defaultImage: "/images/walls/defaultTri2Hop/front-slope",
        completedImage: "/images/walls/completedTri2Hop/front-slope",
        wallDrawings: ["/images/tri/1302-TRI-1.png"],
        specialRequirements: "",
        status: "notStarted",
        startedDate: null,
        completedDate: null,
        isActive: false,
        firstStart: false,
        time: 0,
      },
      {
        wallType: "Rear Slope",
        defaultImage: "/images/walls/defaultTri2Hop/rear-slope",
        completedImage: "/images/walls/completedTri2Hop/rear-slope",
        wallDrawings: ["/images/tri/1305-TRI-1.png"],
        specialRequirements: "",
        status: "notStarted",
        startedDate: null,
        completedDate: null,
        isActive: false,
        firstStart: false,
        time: 0,
      },
      {
        wallType: "Mid Wall",
        defaultImage: "/images/walls/defaultTri2Hop/midwall",
        completedImage: "/images/walls/completedTri2Hop/midwall",
        wallDrawings: ["/images/tri/1303-TRI-2HOPPERSMIDWALL-1.png"],
        specialRequirements: "",
        status: "notStarted",
        startedDate: null,
        completedDate: null,
        isActive: false,
        firstStart: false,
        time: 0,
      },
    ],
  },
  {
    dateRequired: null,
    WO: "45511",
    trailerType: "Tri 3 Hop",
    walls: [
      {
        wallType: "Side Wall - Driver",
        defaultImage: "/images/walls/defaultTri3Hop/driver",
        completedImage: "/images/walls/completedTri3Hop/driver",
        wallDrawings: [
          "/images/tri/1300-TRI-1.png",
          "/images/tri/1300-TRI-2.png",
          "/images/tri/1300-TRI-3.png",
          "/images/tri/1300-TRI-4.png",
          "/images/tri/1300-TRI-5.png",
          "/images/tri/1300-TRI-6.png",
        ],
        specialRequirements: "",
        status: "notStarted",
        startedDate: null,
        completedDate: null,
        isActive: false,
        firstStart: false,
        time: 0,
      },
      {
        wallType: "Side Wall - Passenger",
        defaultImage: "/images/walls/defaultTri3Hop/pass",
        completedImage: "/images/walls/completedTri3Hop/pass",
        wallDrawings: [
          "/images/tri/1300-TRI-1.png",
          "/images/tri/1300-TRI-2.png",
          "/images/tri/1300-TRI-3.png",
          "/images/tri/1300-TRI-4.png",
          "/images/tri/1300-TRI-5.png",
          "/images/tri/1300-TRI-6.png",
        ],
        specialRequirements: "",
        status: "notStarted",
        startedDate: null,
        completedDate: null,
        isActive: false,
        firstStart: false,
        time: 0,
      },
      {
        wallType: "Front Slope",
        defaultImage: "/images/walls/defaultTri3Hop/front-slope",
        completedImage: "/images/walls/completedTri3Hop/front-slope",
        wallDrawings: ["/images/tri/1302-TRI-1.png"],
        specialRequirements: "",
        status: "notStarted",
        startedDate: null,
        completedDate: null,
        isActive: false,
        firstStart: false,
        time: 0,
      },
      {
        wallType: "Rear Slope",
        defaultImage: "/images/walls/defaultTri3Hop/rear-slope",
        completedImage: "/images/walls/completedTri3Hop/rear-slope",
        wallDrawings: ["/images/tri/1305-TRI-1.png"],
        specialRequirements: "",
        status: "notStarted",
        startedDate: null,
        completedDate: null,
        isActive: false,
        firstStart: false,
        time: 0,
      },
      {
        wallType: "Mid Wall",
        defaultImage: "/images/walls/defaultTri3Hop/midwall",
        completedImage: "/images/walls/completedTri3Hop/midwall-1",
        wallDrawings: ["/images/tri/1303-TRI-3HOPPERSMIDWALL-1.png"],
        specialRequirements: "",
        status: "notStarted",
        startedDate: null,
        completedDate: null,
        isActive: false,
        firstStart: false,
        time: 0,
      },
      {
        wallType: "Mid Wall 2",
        defaultImage: "/images/walls/defaultTri3Hop/midwall",
        completedImage: "/images/walls/completedTri3Hop/midwall-2",
        wallDrawings: ["/images/tri/1303-TRI-3HOPPERSMIDWALL-1.png"],
        specialRequirements: "",
        status: "notStarted",
        startedDate: null,
        completedDate: null,
        isActive: false,
        firstStart: false,
        time: 0,
      },
    ],
  },
  {
    dateRequired: null,
    WO: "42162",
    trailerType: "Tandem",
    walls: [
      {
        wallType: "Side Wall - Driver",
        defaultImage: "/images/walls/defaultTandem/driver",
        completedImage: "/images/walls/completedTandem/driver",
        wallDrawings: [
          "/images/tandem/1300-TAN-1.png",
          "/images/tandem/1300-TAN-2.png",
          "/images/tandem/1300-TAN-3.png",
          "/images/tandem/1300-TAN-4.png",
        ],
        specialRequirements: "",
        status: "notStarted",
        startedDate: null,
        completedDate: null,
        isActive: false,
        firstStart: false,
        time: 0,
      },
      {
        wallType: "Side Wall - Passenger",
        defaultImage: "/images/walls/defaultTandem/pass",
        completedImage: "/images/walls/completedTandem/pass",
        wallDrawings: [
          "/images/tandem/1300-TAN-1.png",
          "/images/tandem/1300-TAN-2.png",
          "/images/tandem/1300-TAN-3.png",
          "/images/tandem/1300-TAN-4.png",
        ],
        specialRequirements: "",
        status: "notStarted",
        startedDate: null,
        completedDate: null,
        isActive: false,
        firstStart: false,
        time: 0,
      },
      {
        wallType: "Front Slope",
        defaultImage: "/images/walls/defaultTandem/front-slope",
        completedImage: "/images/walls/completedTandem/front-slope",
        wallDrawings: ["/images/tandem/1302-TAN-1.png"],
        specialRequirements: "",
        status: "notStarted",
        startedDate: null,
        completedDate: null,
        isActive: false,
        firstStart: false,
        time: 0,
      },
      {
        wallType: "Rear Slope",
        defaultImage: "/images/walls/defaultTandem/rear-slope",
        completedImage: "/images/walls/completedTandem/rear-slope",
        wallDrawings: ["/images/tandem/1305-TAN-1.png"],
        specialRequirements: "",
        status: "notStarted",
        startedDate: null,
        completedDate: null,
        isActive: false,
        firstStart: false,
        time: 0,
      },
      {
        wallType: "Mid Wall",
        defaultImage: "/images/walls/defaultTandem/midwall",
        completedImage: "/images/walls/completedTandem/midwall",
        wallDrawings: ["/images/tandem/1303-TAN-1.png"],
        specialRequirements: "",
        status: "notStarted",
        startedDate: null,
        completedDate: null,
        isActive: false,
        firstStart: false,
        time: 0,
      },
    ],
  },
  {
    dateRequired: null,
    WO: "12345",
    trailerType: "4 Axle",
    walls: [
      {
        wallType: "Side Wall - Driver",
        defaultImage: "/images/walls/defaultTandem/driver",
        completedImage: "/images/walls/completedTandem/driver",
        wallDrawings: [
          "/images/tandem/1300-TAN-1.png",
          "/images/tandem/1300-TAN-2.png",
          "/images/tandem/1300-TAN-3.png",
          "/images/tandem/1300-TAN-4.png",
        ],
        specialRequirements: "",
        status: "notStarted",
        startedDate: null,
        completedDate: null,
        isActive: false,
        firstStart: false,
        time: 0,
      },
      {
        wallType: "Side Wall - Passenger",
        defaultImage: "/images/walls/defaultTandem/pass",
        completedImage: "/images/walls/completedTandem/pass",
        wallDrawings: [
          "/images/tandem/1300-TAN-1.png",
          "/images/tandem/1300-TAN-2.png",
          "/images/tandem/1300-TAN-3.png",
          "/images/tandem/1300-TAN-4.png",
        ],
        specialRequirements: "",
        status: "notStarted",
        startedDate: null,
        completedDate: null,
        isActive: false,
        firstStart: false,
        time: 0,
      },
      {
        wallType: "Front Slope",
        defaultImage: "/images/walls/defaultTandem/front-slope",
        completedImage: "/images/walls/completedTandem/front-slope",
        wallDrawings: ["/images/tandem/1302-TAN-1.png"],
        specialRequirements: "",
        status: "notStarted",
        startedDate: null,
        completedDate: null,
        isActive: false,
        firstStart: false,
        time: 0,
      },
      {
        wallType: "Rear Slope",
        defaultImage: "/images/walls/defaultTandem/rear-slope",
        completedImage: "/images/walls/completedTandem/rear-slope",
        wallDrawings: ["/images/tandem/1305-TAN-1.png"],
        specialRequirements: "",
        status: "notStarted",
        startedDate: null,
        completedDate: null,
        isActive: false,
        firstStart: false,
        time: 0,
      },
      {
        wallType: "Mid Wall",
        defaultImage: "/images/walls/defaultTandem/midwall",
        completedImage: "/images/walls/completedTandem/midwall",
        wallDrawings: ["/images/tandem/1303-TAN-1.png"],
        specialRequirements: "",
        status: "notStarted",
        startedDate: null,
        completedDate: null,
        isActive: false,
        firstStart: false,
        time: 0,
      },
    ],
  },
];

export default wallsData;
